namespace: myapp
replicaCount: 2
image:
  repository: rizjosel/spring-petclinic
  tag: 18
  pullPolicy: IfNotPresent
service:
  type: NodePort       # Changeable: ClusterIP / NodePort / LoadBalancer
  port: 80
  nodePort: 30080      # Optional: if empty, Kubernetes assigns a port automatically
containerPort: 8080
