apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic
  namespace: flux-system
spec:
  interval: 5m
  path: ./               # points to folder containing helmrelease.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
