apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic
  namespace: myapp
spec:
  interval: 5m
  path: "./clusters/my-cluster/apps/petclinic"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-app-repo
    namespace: myapp
