apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petclinic.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "petclinic.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "petclinic.name" . }}
    spec:
      containers:
      - name: {{ include "petclinic.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
