apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "petclinic.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - petclinic.local
      secretName: petclinic-tls
  rules:
    - host: petclinic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "petclinic.fullname" . }}-svc
                port:
                  number: {{ .Values.service.port }}
