apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "petclinic.fullname" . }}-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
