apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "petclinic.fullname" . }}-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.service.containerPort }}   
    - name: https
      protocol: TCP
      port: 443
      targetPort: {{ .Values.service.containerPort }}
